stages:
  - build
  - deploy

build:
  stage: build
  image: "rust:latest"
  script:
    - rustup toolchain install nightly
    - cargo +nightly build --release
    - echo "$AWS_EC2_PEM" > atlas-probesim-dev.pem
    - chmod 0400 atlas-probesim-dev.pem
    # - cat ~/.ssh/known_hosts
    # - ssh-keyscan ec2-52-59-192-252.eu-central-1.compute.amazonaws.com
    - scp -o StrictHostKeyChecking=no -o IdentityFile=atlas-probesim-dev.pem target/release/probe-similarity ubuntu@ec2-52-59-192-252.eu-central-1.compute.amazonaws.com:/tmp/